name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
      TARGET: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ env.TARGET }}

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Install TailwindCSS
        run: |
          cd server/web
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss

      - name: Build Server (includes embedded web)
        timeout-minutes: 15
        run: |
          mkdir -p server/build/release
          cargo build --release --target ${{ env.TARGET }} -p bim-server
          cp target/${{ env.TARGET }}/release/bim-server server/build/release/bim-server

      - name: UPX Server
        uses: crazy-max/ghaction-upx@v4
        with:
          version: latest
          files: ./server/build/release/bim-server
          args: --best --lzma

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v7
        with:
          name: server-${{ env.TARGET }}
          path: server/build/release/bim-server

      - name: Build Client
        timeout-minutes: 15
        run: |
          mkdir -p client/build/release
          cargo build --release --target ${{ env.TARGET }} -p bim
          cp target/${{ env.TARGET }}/release/bim client/build/release/bim

      - name: UPX Client
        uses: crazy-max/ghaction-upx@v4
        with:
          version: latest
          files: ./client/build/release/bim
          args: --best --lzma

      - name: Upload Client Artifact
        uses: actions/upload-artifact@v7
        with:
          name: client-${{ env.TARGET }}
          path: client/build/release/bim
