name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies and build
        working-directory: web
        run: |
          npm ci
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: web
          path: web/dist/*

  build-linux-x86_64:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
      TARGET: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ env.TARGET }}

      - name: Install cross
        run: cargo install cross

      - name: Build Server
        timeout-minutes: 15
        working-directory: server
        run: |
          mkdir -p ./build/release
          cross build --target ${{ env.TARGET }} --release
          cp ../../target/${{ env.TARGET }}/release/bim-server ./build/release/bim-server

      - name: UPX Server
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: ./server/build/release/bim-server
          args: --best --lzma

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v7
        with:
          name: server-${{ env.TARGET }}
          path: server/build/release/bim-server

      - name: Build Client
        timeout-minutes: 15
        working-directory: client
        run: |
          mkdir -p build/release
          cross build --target ${{ env.TARGET }} --release
          cp ../../target/${{ env.TARGET }}/release/bim build/release/bim

      - name: UPX Client
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: ./client/build/release/bim
          args: --best --lzma

      - name: Upload Client Artifact
        uses: actions/upload-artifact@v7
        with:
          name: client-${{ env.TARGET }}
          path: client/build/release/*
